language: c

sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository ppa:ondrej/autotools -y # automake 1.15
  - sudo add-apt-repository ppa:cz.nic-labs/knot-dns -y # pkg-config 0.29.2
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake-1.15 pkg-config m4 libsndfile-dev libfftw3-dev libasound2-dev

env:
  - AUTOGEN=true CMAKE_SHARED=OFF
  - AUTOGEN=false CMAKE_SHARED=ON

script:
  - if $AUTOGEN; then ./autogen.sh && ./configure --enable-sndfile --enable-alsa && make distcheck; fi
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=$CMAKE_SHARED ..
  - cat config.h
  - make
  - make test
